# Generated by Django 4.0.4 on 2022-06-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img_gallery',
            old_name='imgages',
            new_name='images',
        ),
    ]
